barChartStats = [{
	"id": 1084,
	"amount": 84,
	"logDate": "16.11.2015",
	"website": {
		"id": 1,
		"active": 1,
		"description": "blabla",
		"domain": "http://pswengi.bamb.at"
	},
	"word": {
		"text": "bee",
		"active": 1
	}
}, {
	"id": 1603,
	"amount": 80,
	"logDate": "16.11.2015",
	"website": {
		"id": 1,
		"active": 1,
		"description": "blabla",
		"domain": "http://pswengi.bamb.at"
	},
	"word": {
		"text": "in",
		"active": 1
	}
}, {
	"id": 1392,
	"amount": 78,
	"logDate": "16.11.2015",
	"website": {
		"id": 1,
		"active": 1,
		"description": "blabla",
		"domain": "http://pswengi.bamb.at"
	},
	"word": {
		"text": "do",
		"active": 1
	}
}, {
	"id": 1830,
	"amount": 71,
	"logDate": "16.11.2015",
	"website": {
		"id": 1,
		"active": 1,
		"description": "blabla",
		"domain": "http://pswengi.bamb.at"
	},
	"word": {
		"text": "die",
		"active": 1
	}
}, {
	"id": 527,
	"amount": 68,
	"logDate": "16.11.2015",
	"website": {
		"id": 1,
		"active": 1,
		"description": "blabla",
		"domain": "http://pswengi.bamb.at"
	},
	"word": {
		"text": "sed",
		"active": 1
	}
}];

siteList = [{
	"id": 1,
	"active": 1,
	"description": "blabla",
	"domain": "http://pswengi.bamb.at"
}];

wordList = [{
	"text": "\"action-points\"",
	"active": 1
}, {
	"text": "\"alte\"",
	"active": 1
}, {
	"text": "\"ark\"",
	"active": 1
}, {
	"text": "\"bei",
	"active": 1
}, {
	"text": "\"best-of\"",
	"active": 1
}, {
	"text": "\"das",
	"active": 1
}, {
	"text": "\"die",
	"active": 1
}, {
	"text": "\"durch",
	"active": 1
}, {
	"text": "\"ein",
	"active": 1
}, {
	"text": "\"elder",
	"active": 1
}, {
	"text": "\"es",
	"active": 1
}, {
	"text": "\"fallout",
	"active": 1
}, {
	"text": "\"fallout\"-spiele",
	"active": 1
}, {
	"text": "\"fallout\"-vorgÃ¤ngern,",
	"active": 1
}, {
	"text": "\"fÃ¼r",
	"active": 1
}, {
	"text": "\"gegen",
	"active": 1
}, {
	"text": "\"ich",
	"active": 1
}, {
	"text": "\"innovationen\"",
	"active": 1
}, {
	"text": "\"institut\"",
	"active": 1
}, {
	"text": "\"perk\"-system",
	"active": 1
}, {
	"text": "\"power",
	"active": 1
}, {
	"text": "\"rust\"",
	"active": 1
}, {
	"text": "\"science\"-schwerpunkt",
	"active": 1
}, {
	"text": "\"skyrim\"",
	"active": 1
}, {
	"text": "\"skyrim\",",
	"active": 1
}, {
	"text": "\"standhaft\"",
	"active": 1
}, {
	"text": "\"stÃ¤hlernen",
	"active": 1
}, {
	"text": "\"the",
	"active": 1
}, {
	"text": "\"v.a.t.s.\"-system",
	"active": 1
}, {
	"text": "\"vaults\"",
	"active": 1
}, {
	"text": "\"war",
	"active": 1
}, {
	"text": "\"wir",
	"active": 1
}, {
	"text": "(rainer",
	"active": 1
}, {
	"text": "(ruinen-)landschaften",
	"active": 1
}, {
	"text": "(zum",
	"active": 1
}, {
	"text": "...",
	"active": 1
}, {
	"text": "09.11.2015",
	"active": 1
}, {
	"text": "1",
	"active": 1
}, {
	"text": "1.760",
	"active": 1
}, {
	"text": "10.",
	"active": 1
}, {
	"text": "102",
	"active": 1
}, {
	"text": "14:00",
	"active": 1
}, {
	"text": "175",
	"active": 1
}, {
	"text": "17:01",
	"active": 1
}, {
	"text": "1938",
	"active": 1
}, {
	"text": "1950er-jahre,",
	"active": 1
}, {
	"text": "1997",
	"active": 1
}, {
	"text": "1998",
	"active": 1
}, {
	"text": "2",
	"active": 1
}, {
	"text": "2008,",
	"active": 1
}, {
	"text": "2015,",
	"active": 1
}, {
	"text": "22",
	"active": 1
}, {
	"text": "3",
	"active": 1
}, {
	"text": "3\"",
	"active": 1
}, {
	"text": "4\r\n",
	"active": 1
}, {
	"text": "4\r\nuntitled",
	"active": 1
}, {
	"text": "4",
	"active": 1
}, {
	"text": "4\"",
	"active": 1
}, {
	"text": "400",
	"active": 1
}, {
	"text": "4bla",
	"active": 1
}, {
	"text": "4wgvweagf",
	"active": 1
}, {
	"text": "59",
	"active": 1
}, {
	"text": "666",
	"active": 1
}, {
	"text": "9.",
	"active": 1
}, {
	"text": "9.11.2015)",
	"active": 1
}, {
	"text": "a",
	"active": 1
}, {
	"text": "a,",
	"active": 1
}, {
	"text": "a.",
	"active": 1
}, {
	"text": "aaaaaah",
	"active": 1
}, {
	"text": "aamoo!",
	"active": 1
}, {
	"text": "ab",
	"active": 1
}, {
	"text": "aber",
	"active": 1
}, {
	"text": "abgelaufen",
	"active": 1
}, {
	"text": "abgeschlossenen",
	"active": 1
}, {
	"text": "abhÃ¤ngig",
	"active": 1
}, {
	"text": "ableger",
	"active": 1
}, {
	"text": "absurd",
	"active": 1
}, {
	"text": "abtragungsvarianten",
	"active": 1
}, {
	"text": "abwechslung",
	"active": 1
}, {
	"text": "abwechslungsreiche",
	"active": 1
}, {
	"text": "ac",
	"active": 1
}, {
	"text": "ac,",
	"active": 1
}, {
	"text": "ac.",
	"active": 1
}, {
	"text": "accumsan",
	"active": 1
}, {
	"text": "accumsan.",
	"active": 1
}, {
	"text": "acham",
	"active": 1
}, {
	"text": "ackerflÃ¤chen,",
	"active": 1
}, {
	"text": "ad",
	"active": 1
}, {
	"text": "ad.",
	"active": 1
}, {
	"text": "adipiscing",
	"active": 1
}, {
	"text": "adipisicing",
	"active": 1
}, {
	"text": "aenean",
	"active": 1
}, {
	"text": "aktivieren,",
	"active": 1
}, {
	"text": "aktualisiert:",
	"active": 1
}, {
	"text": "aliqua",
	"active": 1
}, {
	"text": "aliquam",
	"active": 1
}, {
	"text": "aliquet",
	"active": 1
}, {
	"text": "aliquet,",
	"active": 1
}, {
	"text": "aliquip",
	"active": 1
}, {
	"text": "aliquip.",
	"active": 1
}, {
	"text": "alle",
	"active": 1
}, {
	"text": "allem",
	"active": 1
}, {
	"text": "allen",
	"active": 1
}, {
	"text": "aller",
	"active": 1
}, {
	"text": "allerdings",
	"active": 1
}, {
	"text": "alles",
	"active": 1
}, {
	"text": "als",
	"active": 1
}, {
	"text": "also",
	"active": 1
}, {
	"text": "altbekanntes",
	"active": 1
}, {
	"text": "alten",
	"active": 1
}, {
	"text": "altkanzler",
	"active": 1
}, {
	"text": "am",
	"active": 1
}, {
	"text": "amerika",
	"active": 1
}, {
	"text": "amerikaner",
	"active": 1
}, {
	"text": "amet",
	"active": 1
}, {
	"text": "amet,",
	"active": 1
}, {
	"text": "amet.",
	"active": 1
}, {
	"text": "an",
	"active": 1
}, {
	"text": "an,",
	"active": 1
}, {
	"text": "an.",
	"active": 1
}, {
	"text": "anbeginn",
	"active": 1
}, {
	"text": "anderen",
	"active": 1
}, {
	"text": "andrea",
	"active": 1
}, {
	"text": "anfang",
	"active": 1
}, {
	"text": "angegangen",
	"active": 1
}, {
	"text": "angesprengt",
	"active": 1
}, {
	"text": "angestellt,",
	"active": 1
}, {
	"text": "angreifende",
	"active": 1
}, {
	"text": "anlage,",
	"active": 1
}, {
	"text": "anrainer",
	"active": 1
}, {
	"text": "anrainerin",
	"active": 1
}, {
	"text": "anschauen.",
	"active": 1
}, {
	"text": "ante",
	"active": 1
}, {
	"text": "ante,",
	"active": 1
}, {
	"text": "ante.",
	"active": 1
}, {
	"text": "anteil",
	"active": 1
}, {
	"text": "anwachsenden",
	"active": 1
}, {
	"text": "anzahl",
	"active": 1
}, {
	"text": "apa.",
	"active": 1
}, {
	"text": "aptent",
	"active": 1
}, {
	"text": "arbeiten",
	"active": 1
}, {
	"text": "arcu",
	"active": 1
}, {
	"text": "arcu,",
	"active": 1
}, {
	"text": "arcu.",
	"active": 1
}, {
	"text": "areals",
	"active": 1
}, {
	"text": "arge",
	"active": 1
}, {
	"text": "armor\"",
	"active": 1
}, {
	"text": "art",
	"active": 1
}, {
	"text": "article",
	"active": 1
}, {
	"text": "at",
	"active": 1
}, {
	"text": "at,",
	"active": 1
}, {
	"text": "at.",
	"active": 1
}, {
	"text": "atemlose",
	"active": 1
}, {
	"text": "athen",
	"active": 1
}, {
	"text": "atmosphÃ¤re:",
	"active": 1
}, {
	"text": "atomaren",
	"active": 1
}, {
	"text": "atombunkers",
	"active": 1
}, {
	"text": "atompilze",
	"active": 1
}, {
	"text": "atomsicheren",
	"active": 1
}, {
	"text": "auch",
	"active": 1
}, {
	"text": "auch,",
	"active": 1
}, {
	"text": "auctor",
	"active": 1
}, {
	"text": "auf",
	"active": 1
}, {
	"text": "auf.",
	"active": 1
}, {
	"text": "auffindbar",
	"active": 1
}, {
	"text": "auffindbaren",
	"active": 1
}, {
	"text": "aufgehÃ¼bschtes",
	"active": 1
}, {
	"text": "auflockerung",
	"active": 1
}, {
	"text": "aufregenden",
	"active": 1
}, {
	"text": "aufsteigen,",
	"active": 1
}, {
	"text": "aufstiegshilfen",
	"active": 1
}, {
	"text": "auftrÃ¤ge",
	"active": 1
}, {
	"text": "aufwarten",
	"active": 1
}, {
	"text": "aufzuhalten.",
	"active": 1
}, {
	"text": "augue",
	"active": 1
}, {
	"text": "augue,",
	"active": 1
}, {
	"text": "augue.",
	"active": 1
}, {
	"text": "aus",
	"active": 1
}, {
	"text": "aus,",
	"active": 1
}, {
	"text": "aus.\"",
	"active": 1
}, {
	"text": "ausbauen",
	"active": 1
}, {
	"text": "ausbauen,",
	"active": 1
}, {
	"text": "ausflÃ¼ge",
	"active": 1
}, {
	"text": "ausland",
	"active": 1
}, {
	"text": "ausrÃ¼stung",
	"active": 1
}, {
	"text": "aussagen",
	"active": 1
}, {
	"text": "aussendung",
	"active": 1
}, {
	"text": "auszubauen",
	"active": 1
}, {
	"text": "auszubauende",
	"active": 1
}, {
	"text": "aute",
	"active": 1
}, {
	"text": "auto",
	"active": 1
}, {
	"text": "auÃŸerhalb",
	"active": 1
}, {
	"text": "awertbdf",
	"active": 1
}, {
	"text": "b",
	"active": 1
}, {
	"text": "b4",
	"active": 1
}, {
	"text": "b4twzrhbdsvela",
	"active": 1
}, {
	"text": "b4tz5sr6jzmnfhgla",
	"active": 1
}, {
	"text": "b5hr5es7z5shla",
	"active": 1
}, {
	"text": "b65iu56rdt74la",
	"active": 1
}, {
	"text": "b6dt8ijtdrs56tz5la",
	"active": 1
}, {
	"text": "b6e5l56ujh45rhta",
	"active": 1
}, {
	"text": "b6si7dtkumznhgla",
	"active": 1
}, {
	"text": "b8udrh657z4ula",
	"active": 1
}, {
	"text": "baboiii",
	"active": 1
}, {
	"text": "baby",
	"active": 1
}, {
	"text": "baerwthla",
	"active": 1
}, {
	"text": "baeryhgbdsvsla",
	"active": 1
}, {
	"text": "bahnbrechenden",
	"active": 1
}, {
	"text": "bala",
	"active": 1
}, {
	"text": "balance",
	"active": 1
}, {
	"text": "bananaaa!",
	"active": 1
}, {
	"text": "bananaaaa",
	"active": 1
}, {
	"text": "bananaaaa.",
	"active": 1
}, {
	"text": "banditen",
	"active": 1
}, {
	"text": "bann",
	"active": 1
}, {
	"text": "bappleees",
	"active": 1
}, {
	"text": "basen",
	"active": 1
}, {
	"text": "bau",
	"active": 1
}, {
	"text": "bau-interface",
	"active": 1
}, {
	"text": "bauaufsicht",
	"active": 1
}, {
	"text": "bauchschmerzen",
	"active": 1
}, {
	"text": "bauer",
	"active": 1
}, {
	"text": "bauten",
	"active": 1
}, {
	"text": "bbdf",
	"active": 1
}, {
	"text": "bbdtr6i7tf8lzui,mgla",
	"active": 1
}, {
	"text": "bbrgefrw5te6rz7tukla",
	"active": 1
}, {
	"text": "bbs",
	"active": 1
}, {
	"text": "bdfbdbysdv",
	"active": 1
}, {
	"text": "bdhnbvsfewgla",
	"active": 1
}, {
	"text": "bdnbsvaela",
	"active": 1
}, {
	"text": "bdrtxjfk8llzk,la",
	"active": 1
}, {
	"text": "bdtnbrstla",
	"active": 1
}, {
	"text": "bdvaegarh5tue6jla",
	"active": 1
}, {
	"text": "beabsichtigten",
	"active": 1
}, {
	"text": "beate",
	"active": 1
}, {
	"text": "bedauerlich,",
	"active": 1
}, {
	"text": "bedenken,",
	"active": 1
}, {
	"text": "bedienenden",
	"active": 1
}, {
	"text": "bedrohen",
	"active": 1
}, {
	"text": "bee",
	"active": 1
}, {
	"text": "begeistern.",
	"active": 1
}, {
	"text": "beginn",
	"active": 1
}, {
	"text": "beginnenden",
	"active": 1
}, {
	"text": "begutachten,",
	"active": 1
}, {
	"text": "begutachtung",
	"active": 1
}, {
	"text": "begwaa",
	"active": 1
}, {
	"text": "behydbs",
	"active": 1
}, {
	"text": "bei",
	"active": 1
}, {
	"text": "beide",
	"active": 1
}, {
	"text": "beiden",
	"active": 1
}, {
	"text": "beim",
	"active": 1
}, {
	"text": "beispiel",
	"active": 1
}, {
	"text": "bejahrten",
	"active": 1
}, {
	"text": "bekannt",
	"active": 1
}, {
	"text": "bekannten",
	"active": 1
}, {
	"text": "belloo!",
	"active": 1
}, {
	"text": "bemÃ¼hungen",
	"active": 1
}, {
	"text": "benzinkanister",
	"active": 1
}, {
	"text": "bereiten",
	"active": 1
}, {
	"text": "bereits",
	"active": 1
}, {
	"text": "berichtet",
	"active": 1
}, {
	"text": "beruhigt",
	"active": 1
}, {
	"text": "beschÃ¤ftigungsangebot",
	"active": 1
}, {
	"text": "besichtigung",
	"active": 1
}, {
	"text": "besprochen,",
	"active": 1
}, {
	"text": "beste",
	"active": 1
}, {
	"text": "bestehe",
	"active": 1
}, {
	"text": "besteht",
	"active": 1
}, {
	"text": "bestem",
	"active": 1
}, {
	"text": "besten",
	"active": 1
}, {
	"text": "bestimmt",
	"active": 1
}, {
	"text": "bestimmten",
	"active": 1
}, {
	"text": "bestrahlte",
	"active": 1
}, {
	"text": "bestreben,",
	"active": 1
}, {
	"text": "bethesda",
	"active": 1
}, {
	"text": "bethesda-rollenspiele,",
	"active": 1
}, {
	"text": "bethesda-spiel",
	"active": 1
}, {
	"text": "bethesda-typischen",
	"active": 1
}, {
	"text": "beton",
	"active": 1
}, {
	"text": "betrachtung",
	"active": 1
}, {
	"text": "betreten",
	"active": 1
}, {
	"text": "betrifft.",
	"active": 1
}, {
	"text": "betroffenen.",
	"active": 1
}, {
	"text": "betrunkener",
	"active": 1
}, {
	"text": "bevÃ¶lkert",
	"active": 1
}, {
	"text": "bevÃ¶lkerung",
	"active": 1
}, {
	"text": "bewachtes",
	"active": 1
}, {
	"text": "bewegen",
	"active": 1
}, {
	"text": "bewohnern",
	"active": 1
}, {
	"text": "bewÃ¤hrten,",
	"active": 1
}, {
	"text": "bewÃ¤hrtes",
	"active": 1
}, {
	"text": "bezeichnet",
	"active": 1
}, {
	"text": "bfarhtndbsvla",
	"active": 1
}, {
	"text": "bfhmngdsew45e6riz7kmla",
	"active": 1
}, {
	"text": "bfo98luimgzfla",
	"active": 1
}, {
	"text": "bfvaeyv",
	"active": 1
}, {
	"text": "bgf4we",
	"active": 1
}, {
	"text": "bhjr68kl8zufnla",
	"active": 1
}, {
	"text": "bhndbsvaewqla",
	"active": 1
}, {
	"text": "bhntrg5s6rid7tkla",
	"active": 1
}, {
	"text": "bibendum",
	"active": 1
}, {
	"text": "bibendum,",
	"active": 1
}, {
	"text": "bieten,",
	"active": 1
}, {
	"text": "bietet",
	"active": 1
}, {
	"text": "bietet:",
	"active": 1
}, {
	"text": "bis",
	"active": 1
}, {
	"text": "bl6rhtbdrzhta",
	"active": 1
}, {
	"text": "bl809Ã¼pÃ¶8z9ulzkzjtha",
	"active": 1
}, {
	"text": "bl8di67fo8ktjz64a",
	"active": 1
}, {
	"text": "bl8ul,mzntbrw5a",
	"active": 1
}, {
	"text": "bla",
	"active": 1
}, {
	"text": "bla4ewgvsda",
	"active": 1
}, {
	"text": "blabsrvearhtj",
	"active": 1
}, {
	"text": "blandit",
	"active": 1
}, {
	"text": "blandit,",
	"active": 1
}, {
	"text": "bldr6irtuidt7a",
	"active": 1
}, {
	"text": "bldrgbtukuta",
	"active": 1
}, {
	"text": "bldtuor7rzjutta",
	"active": 1
}, {
	"text": "bleiben",
	"active": 1
}, {
	"text": "bleibt",
	"active": 1
}, {
	"text": "blfhng",
	"active": 1
}, {
	"text": "blghrjtea",
	"active": 1
}, {
	"text": "blgrhtjzkutzmfngdta",
	"active": 1
}, {
	"text": "blieb",
	"active": 1
}, {
	"text": "blrhtdnfgba",
	"active": 1
}, {
	"text": "bls",
	"active": 1
}, {
	"text": "blsbv",
	"active": 1
}, {
	"text": "bltq234wfecvbtzuklza",
	"active": 1
}, {
	"text": "bltrhsbtdsra",
	"active": 1
}, {
	"text": "blub",
	"active": 1
}, {
	"text": "blukmzfhngdbrsefla",
	"active": 1
}, {
	"text": "bodaaa",
	"active": 1
}, {
	"text": "bofitzla",
	"active": 1
}, {
	"text": "boko",
	"active": 1
}, {
	"text": "bombe",
	"active": 1
}, {
	"text": "boston",
	"active": 1
}, {
	"text": "braucht",
	"active": 1
}, {
	"text": "bruchteil",
	"active": 1
}, {
	"text": "bruderschaft\",",
	"active": 1
}, {
	"text": "bsdbvsyf",
	"active": 1
}, {
	"text": "bsdvae4w5ue6ir7tla",
	"active": 1
}, {
	"text": "bsioutdgrsvcqwdefrgtzjukla",
	"active": 1
}, {
	"text": "bsvdgala",
	"active": 1
}, {
	"text": "bth576k8tjuzftla",
	"active": 1
}, {
	"text": "bu9zlu,gziula",
	"active": 1
}, {
	"text": "bundesheer",
	"active": 1
}, {
	"text": "bundesheer.",
	"active": 1
}, {
	"text": "bundesheers",
	"active": 1
}, {
	"text": "bundesliga:",
	"active": 1
}, {
	"text": "bunkers",
	"active": 1
}, {
	"text": "bunte",
	"active": 1
}, {
	"text": "butt",
	"active": 1
}, {
	"text": "butt.",
	"active": 1
}, {
	"text": "bwa%euthnbdrvsela",
	"active": 1
}, {
	"text": "bwrevsvarewg4rsvla",
	"active": 1
}, {
	"text": "bz90pÃ¶lla",
	"active": 1
}, {
	"text": "bzgfdhg54wu6jrla",
	"active": 1
}, {
	"text": "bÃ¤Ã¼pÃ¶olikujzgrfedla",
	"active": 1
}, {
	"text": "bÃ¤Ã¼Ã¶polikujzhgtrfedla",
	"active": 1
}, {
	"text": "camps",
	"active": 1
}, {
	"text": "candy",
	"active": 1
}, {
	"text": "cartoon-figuren",
	"active": 1
}, {
	"text": "cescutti",
	"active": 1
}, {
	"text": "changes\":",
	"active": 1
}, {
	"text": "changes\"?",
	"active": 1
}, {
	"text": "chaos",
	"active": 1
}, {
	"text": "charakter",
	"active": 1
}, {
	"text": "charakter-",
	"active": 1
}, {
	"text": "charakteren,",
	"active": 1
}, {
	"text": "charaktererstellung",
	"active": 1
}, {
	"text": "charakteristische",
	"active": 1
}, {
	"text": "charakterspezifische",
	"active": 1
}, {
	"text": "charaktersystem",
	"active": 1
}, {
	"text": "charismatischer",
	"active": 1
}, {
	"text": "chasy",
	"active": 1
}, {
	"text": "chasy.",
	"active": 1
}, {
	"text": "christian",
	"active": 1
}, {
	"text": "chronik",
	"active": 1
}, {
	"text": "cillum",
	"active": 1
}, {
	"text": "cillum.",
	"active": 1
}, {
	"text": "class",
	"active": 1
}, {
	"text": "commodo",
	"active": 1
}, {
	"text": "commodo.",
	"active": 1
}, {
	"text": "condimentum",
	"active": 1
}, {
	"text": "condimentum,",
	"active": 1
}, {
	"text": "condimentum.",
	"active": 1
}, {
	"text": "congue",
	"active": 1
}, {
	"text": "congue.",
	"active": 1
}, {
	"text": "consectetur",
	"active": 1
}, {
	"text": "consectetur.",
	"active": 1
}, {
	"text": "consequat",
	"active": 1
}, {
	"text": "consequat.",
	"active": 1
}, {
	"text": "conubia",
	"active": 1
}, {
	"text": "convallis",
	"active": 1
}, {
	"text": "convallis.",
	"active": 1
}, {
	"text": "crafting",
	"active": 1
}, {
	"text": "cras",
	"active": 1
}, {
	"text": "cubilia",
	"active": 1
}, {
	"text": "cum",
	"active": 1
}, {
	"text": "curabitur",
	"active": 1
}, {
	"text": "curae;",
	"active": 1
}, {
	"text": "cursus",
	"active": 1
}, {
	"text": "da",
	"active": 1
}, {
	"text": "daa",
	"active": 1
}, {
	"text": "daa.",
	"active": 1
}, {
	"text": "dachte",
	"active": 1
}, {
	"text": "dadurch,",
	"active": 1
}, {
	"text": "dafÃ¼r",
	"active": 1
}, {
	"text": "danach",
	"active": 1
}, {
	"text": "dank",
	"active": 1
}, {
	"text": "dann",
	"active": 1
}, {
	"text": "dapibus",
	"active": 1
}, {
	"text": "dapibus.",
	"active": 1
}, {
	"text": "darf",
	"active": 1
}, {
	"text": "darf:",
	"active": 1
}, {
	"text": "das",
	"active": 1
}, {
	"text": "dass",
	"active": 1
}, {
	"text": "dauer",
	"active": 1
}, {
	"text": "dauern.\"",
	"active": 1
}, {
	"text": "davon",
	"active": 1
}, {
	"text": "deckel",
	"active": 1
}, {
	"text": "dem",
	"active": 1
}, {
	"text": "demnach",
	"active": 1
}, {
	"text": "demnÃ¤chst",
	"active": 1
}, {
	"text": "demontage",
	"active": 1
}, {
	"text": "demselben,",
	"active": 1
}, {
	"text": "den",
	"active": 1
}, {
	"text": "denen",
	"active": 1
}, {
	"text": "denn",
	"active": 1
}, {
	"text": "dennoch",
	"active": 1
}, {
	"text": "der",
	"active": 1
}, {
	"text": "derartigen",
	"active": 1
}, {
	"text": "deren",
	"active": 1
}, {
	"text": "derzeit",
	"active": 1
}, {
	"text": "des",
	"active": 1
}, {
	"text": "deshalb",
	"active": 1
}, {
	"text": "detailbesichtigung",
	"active": 1
}, {
	"text": "detailkenntnissen",
	"active": 1
}, {
	"text": "detailkritik",
	"active": 1
}, {
	"text": "detaillierten",
	"active": 1
}, {
	"text": "detoniert",
	"active": 1
}, {
	"text": "detoniert.",
	"active": 1
}, {
	"text": "deutlich",
	"active": 1
}, {
	"text": "deutlichen",
	"active": 1
}, {
	"text": "deutschen",
	"active": 1
}, {
	"text": "dfbderzd",
	"active": 1
}, {
	"text": "dgw4arvsbla",
	"active": 1
}, {
	"text": "di",
	"active": 1
}, {
	"text": "dialogsystem",
	"active": 1
}, {
	"text": "diam",
	"active": 1
}, {
	"text": "diam,",
	"active": 1
}, {
	"text": "diam.",
	"active": 1
}, {
	"text": "dictum",
	"active": 1
}, {
	"text": "dictum,",
	"active": 1
}, {
	"text": "dictum.",
	"active": 1
}, {
	"text": "die",
	"active": 1
}, {
	"text": "dies",
	"active": 1
}, {
	"text": "diese",
	"active": 1
}, {
	"text": "diesem",
	"active": 1
}, {
	"text": "diesen",
	"active": 1
}, {
	"text": "dieser",
	"active": 1
}, {
	"text": "dieses",
	"active": 1
}, {
	"text": "diesmal",
	"active": 1
}, {
	"text": "dignissim",
	"active": 1
}, {
	"text": "dignissim,",
	"active": 1
}, {
	"text": "direkt",
	"active": 1
}, {
	"text": "direkten",
	"active": 1
}, {
	"text": "dis",
	"active": 1
}, {
	"text": "do",
	"active": 1
}, {
	"text": "do.",
	"active": 1
}, {
	"text": "doch",
	"active": 1
}, {
	"text": "document",
	"active": 1
}, {
	"text": "dolor",
	"active": 1
}, {
	"text": "dolor,",
	"active": 1
}, {
	"text": "dolore",
	"active": 1
}, {
	"text": "dolore.",
	"active": 1
}, {
	"text": "donec",
	"active": 1
}, {
	"text": "drei",
	"active": 1
}, {
	"text": "drohnen",
	"active": 1
}, {
	"text": "druckwellen",
	"active": 1
}, {
	"text": "dsvrew45eta",
	"active": 1
}, {
	"text": "dui",
	"active": 1
}, {
	"text": "dui,",
	"active": 1
}, {
	"text": "dui.",
	"active": 1
}, {
	"text": "duis",
	"active": 1
}, {
	"text": "dul",
	"active": 1
}, {
	"text": "durch",
	"active": 1
}, {
	"text": "durchaus",
	"active": 1
}, {
	"text": "durchgefÃ¼hrt",
	"active": 1
}, {
	"text": "durchsuchen",
	"active": 1
}, {
	"text": "durchtrennen.",
	"active": 1
}, {
	"text": "durchtrennt",
	"active": 1
}, {
	"text": "durchtrennt,",
	"active": 1
}, {
	"text": "durchtrenntfoto",
	"active": 1
}, {
	"text": "durchtrenntnicht",
	"active": 1
}, {
	"text": "dvb",
	"active": 1
}, {
	"text": "dÃ¼rften",
	"active": 1
}, {
	"text": "ebenfalls",
	"active": 1
}, {
	"text": "echtzeit-feuergefechte",
	"active": 1
}, {
	"text": "effekte",
	"active": 1
}];

var siteListTable;
var siteListEditor;

var wordListTable;

$(document).ready(function () {

	// First
	generateSiteListTable();
	// Second
	generateWordsTable();
	// Third
	generateCharts();

});

function generateSiteListTable() {

	siteListEditor = new $.fn.dataTable.Editor( {
		ajax: function ( method, url, d, successCallback, errorCallback ) {


			if ( d.action === 'create' ) {
				console.log(JSON.stringify(d.data[0]))
				var data = d.data[0];
				$.ajax({
					type: "POST",
					url: "./rest/website",
					data: JSON.stringify(data),
					success: successCallback,
					error: errorCallback,
					contentType: "application/json",
				});
			}
			else if ( d.action === 'edit' ) {
				console.log(JSON.stringify(d.data))
				var data = d.data;
				$.ajax({
					type: "PUT", 
					url: "./rest/website",
					data: JSON.stringify(data),
					success: successCallback,
					error: errorCallback,
					contentType: "application/json",
				});
			}
			else if ( d.action === 'remove' ) {
				console.log(JSON.stringify(d.data))
				$.ajax({
					type: "DELETE", 
					url: "./rest/website",
					data: JSON.stringify(d.data),
					success: successCallback,
					error: errorCallback,
					contentType: "application/json",
				});
			}


		},
		idSrc: "id",
		table: "#site-list-table",
		fields: [ {
			label: "Adress:",
			name: "address"
		}, {
			label: "Description",
			name: "description"
		}, {
			label: "Crawldepth",
			name: "depth"
		}, {
			label: "Active",
			name: "active",
			type: "checkbox",
			options:   [
			            { label: '', value: 1 }
			            ]
		}
		]
	} );



	//console.log(tableData);
	siteListTable = $('#site-list-table').DataTable({
		dom: "Bfrtip",
		ajax: "./rest/website", 
		columns: [
		          { data: "id" },
		          { data: "address" },
		          { data: "description" },
		          { data: "depth" },
		          { data: "active" },
		          { data: null }
		          //add render function for button
		          ],
		          columnDefs: 
		        	  [
		        	   {	render: function ( data, type, row ) {
		        		   return "<a class='btn btn-primary' href='./SiteOverview/"+row.id+"'>Details</a>"
		        	   },
		        	   targets: 5 }
		        	   ],
		        	   select: 'single',
		        	   buttons: [
		        	             { extend: "create", editor: siteListEditor },
		        	             { extend: "edit",   editor: siteListEditor },
		        	             { extend: "remove", editor: siteListEditor }
		        	             ]
	} );
}

function generateWordsTable() {
	wordListTable = $('#word-list-table').DataTable({
		dom: "frtip",
		ajax: "./rest/word", 
		order: [[ 1, "desc" ]],
		columns: [
		          { data: "word" },
		          { data: "amount" },
		          { data: "active" },
		          { data: null}
		          //add render function
		          ],
		          columnDefs: 
		        	  [
		        	   {	render: function ( data, type, row ) {
		        		   				return "<a class='btn btn-primary' href='./WordOverview/"+row.word+"'>Details</a>"
		        	   },
		        	   targets: 3 }
		        	   ],
		          select: 'single'

	} );
}
